[0KRunning with gitlab-runner 18.3.0 (9ba718cd)[0;m
[0K  on devsecops ZwJcSyn4P, system ID: r_IcypqJYchyXa[0;m
section_start:1756748788:prepare_executor[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image docker:latest ...[0;m
[0KStarting service docker:dind...[0;m
[0KUsing effective pull policy of [always] for container docker:dind[0;m
[0KPulling docker image docker:dind ...[0;m
[0KUsing docker image sha256:b2a8bf985f76be7345c0c827c568db287ccb4dfad919a4693488224e3644fb0c for docker:dind with digest docker@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de ...[0;m
[0KWaiting for services to be up and running (timeout 30 seconds)...[0;m

[0;33m*** WARNING:[0;m Service runner-zwjcsyn4p-project-1-concurrent-0-50276ac1ece87fce-docker-0 probably didn't start properly.

Health check error:
start service container: Error response from daemon: Cannot link to a non running container: /runner-zwjcsyn4p-project-1-concurrent-0-50276ac1ece87fce-docker-0 AS /runner-zwjcsyn4p-project-1-concurrent-0-50276ac1ece87fce-docker-0-wait-for-service/service (services.go:215:0s)

Service container logs:
2025-09-01T17:46:33.098923610Z ip: can't find device 'nf_tables'
2025-09-01T17:46:33.100260549Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:46:33.102909337Z ip: can't find device 'ip_tables'
2025-09-01T17:46:33.104594129Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:46:33.106282208Z ip: can't find device 'ip6_tables'
2025-09-01T17:46:33.107805018Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:46:33.111007581Z iptables v1.8.11 (nf_tables)
2025-09-01T17:46:33.116316595Z mount: permission denied (are you root?)

[0;33m*********[0;m

[0KUsing effective pull policy of [always] for container docker:latest[0;m
[0KPulling docker image docker:latest ...[0;m
[0KUsing docker image sha256:b2a8bf985f76be7345c0c827c568db287ccb4dfad919a4693488224e3644fb0c for docker:latest with digest docker@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de ...[0;m
section_end:1756748796:prepare_executor[0Ksection_start:1756748796:prepare_script[0K[0K[36;1mPreparing environment[0;m[0;m
[0KUsing effective pull policy of [always] for container sha256:c909dca3aaaed2a2f10fa96499aee4c9f51fb469c8e8ec2a96059c2172d6b72c[0;m
Running on runner-zwjcsyn4p-project-1-concurrent-0 via 38dabeac2d2a...
section_end:1756748797:prepare_script[0Ksection_start:1756748797:get_sources[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mGitaly correlation ID: 01K4366BXD1JJDP9EFJB63W6TZ[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/root/devsecops/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out dc271ce1 as detached HEAD (ref is master)...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1756748799:get_sources[0Ksection_start:1756748799:step_script[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing effective pull policy of [always] for container docker:latest[0;m
[0KUsing docker image sha256:b2a8bf985f76be7345c0c827c568db287ccb4dfad919a4693488224e3644fb0c for docker:latest with digest docker@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de ...[0;m
[32;1m$ sleep 5[0;m
[32;1m$ echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $REGISTRY_URL[0;m
time="2025-09-01T17:46:44Z" level=info msg="Error logging in to endpoint, trying next endpoint" endpoint="{false https://gitlab:5050 false false false 0xc00020e1e0}" error="Get \"https://gitlab:5050/v2/\": dial tcp: lookup gitlab on 8.8.8.8:53: no such host"
Get "https://gitlab:5050/v2/": dial tcp: lookup gitlab on 8.8.8.8:53: no such host
section_end:1756748805:step_script[0Ksection_start:1756748805:cleanup_file_variables[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1756748806:cleanup_file_variables[0K[31;1mERROR: Job failed: exit code 1
[0;m
