[0KRunning with gitlab-runner 18.3.0 (9ba718cd)[0;m
[0K  on devsecops ZwJcSyn4P, system ID: r_IcypqJYchyXa[0;m
section_start:1756747452:prepare_executor[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image docker:latest ...[0;m
[0KStarting service docker:dind...[0;m
[0KUsing effective pull policy of [always] for container docker:dind[0;m
[0KPulling docker image docker:dind ...[0;m
[0KUsing docker image sha256:b2a8bf985f76be7345c0c827c568db287ccb4dfad919a4693488224e3644fb0c for docker:dind with digest docker@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de ...[0;m
[0KWaiting for services to be up and running (timeout 30 seconds)...[0;m

[0;33m*** WARNING:[0;m Service runner-zwjcsyn4p-project-1-concurrent-0-6903d5cca4f4a2de-docker-0 probably didn't start properly.

Health check error:
start service container: Error response from daemon: Cannot link to a non running container: /runner-zwjcsyn4p-project-1-concurrent-0-6903d5cca4f4a2de-docker-0 AS /runner-zwjcsyn4p-project-1-concurrent-0-6903d5cca4f4a2de-docker-0-wait-for-service/service (services.go:215:0s)

Service container logs:
2025-09-01T17:24:19.389679832Z ip: can't find device 'nf_tables'
2025-09-01T17:24:19.392249263Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:24:19.396473245Z ip: can't find device 'ip_tables'
2025-09-01T17:24:19.400020162Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:24:19.402514410Z ip: can't find device 'ip6_tables'
2025-09-01T17:24:19.404589458Z modprobe: can't change directory to '/lib/modules': No such file or directory
2025-09-01T17:24:19.408665855Z iptables v1.8.11 (nf_tables)
2025-09-01T17:24:19.414494722Z mount: permission denied (are you root?)

[0;33m*********[0;m

[0KUsing effective pull policy of [always] for container docker:latest[0;m
[0KPulling docker image docker:latest ...[0;m
[0KUsing docker image sha256:b2a8bf985f76be7345c0c827c568db287ccb4dfad919a4693488224e3644fb0c for docker:latest with digest docker@sha256:c0872aae4791ff427e6eda52769afa04f17b5cf756f8267e0d52774c99d5c9de ...[0;m
section_end:1756747462:prepare_executor[0Ksection_start:1756747462:prepare_script[0K[0K[36;1mPreparing environment[0;m[0;m
[0KUsing effective pull policy of [always] for container sha256:c909dca3aaaed2a2f10fa96499aee4c9f51fb469c8e8ec2a96059c2172d6b72c[0;m
Running on runner-zwjcsyn4p-project-1-concurrent-0 via 38dabeac2d2a...
section_end:1756747464:prepare_script[0Ksection_start:1756747464:get_sources[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mGitaly correlation ID: 01K434XFQ1GBBPZCR702Q5MB48[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/root/devsecops/.git/
[32;1mCreated fresh repository.[0;m
fatal: unable to access 'http://gitlab:8099/root/devsecops.git/': Could not resolve host: gitlab
section_end:1756747465:get_sources[0K[32;1mRetrying in 5s[0;m
section_start:1756747470:cleanup_file_variables[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1756747472:cleanup_file_variables[0K[31;1mERROR: Job failed: exit code 1
[0;m
